name: Linter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
        env:
          CI: true
      - name: Coverage
        run: npx nyc --reporter=lcovonly npm test
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
